version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "8080:80" # Expose l'application sur le port 8080
    volumes:
      - ./:/var/www/html # Monte les fichiers locaux dans le conteneur
    depends_on:
      - db # Démarre le conteneur db avant
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root # Mot de passe root MySQL
      MYSQL_DATABASE: click_and_eat # Nom de la base de données
    ports:
      - "3308:3306" # Expose le serveur MySQL sur le port 3308
    volumes:
      - db_data:/var/lib/mysql # Persiste les données MySQL
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db # Nom du service MySQL
      PMA_PORT: 3306
      PMA_USER: root # Utilisateur MySQL
      PMA_PASSWORD: root # Mot de passe MySQL
    ports:
      - "8081:80" # Expose phpMyAdmin sur le port 8081
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
